services:
    enuyguncom_doctrine_encrypt.orm_subscriber:
        class: EnuygunCom\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@annotation_reader", %enuyguncom_doctrine_encrypt.encryptor_class_name%, %enuyguncom_doctrine_encrypt.secret_key%]
        tags:
            -  { name: doctrine.event_subscriber }
    enuyguncom_doctrine_encrypt.subscriber:
        alias: enuyguncom_doctrine_encrypt.orm_subscriber